permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '7 7 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: Check-Install
jobs:
  check-install:
    runs-on: ubuntu-latest
    name: check-installation 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install
        run: sh setup.sh
      - name: Verbose output
        run: |
          exa --tree ~/.codespace/bin/ # list all the binaries
      - name: Check Install
        run: bash check.sh
