permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  check-install:
    runs-on: ubuntu-latest
    name: check-installation 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install
        run: sh setup.sh
      - name: Check Install
        run: bash check.sh
