permissions:
  contents: read
on:
  push:
    branches: [ master ]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: check-installation 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
